name: Run tests

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
push:
pull_requests:
workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Yarn install
      run: yarn

    - name: Lint
      run: yarn lint

    - name: Run tests
      run: yarn test

    - name: Build
      run: yarn build

